name: 🐛 Bug report
description: Create a report to help us improve

body:

  - type: markdown
    attributes:
      value: |
        Before you submit an issue we recommend you visit [Fastify Help](https://github.com/fastify/help)
        if you have any questions regarding using Fastify.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      options:
      - label: I have written a descriptive issue title
        required: true
      - label: | 
          I have searched existing issues to ensure the bug has not already been reported
        required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: |
        List of steps that reproduces the behavior.
        Make sure you place a stack trace inside a [code (```) block](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) to avoid linking unrelated issues.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
